config/routes.rb
DynamicTicketingSystem::Application.routes.draw do

  get "tickets/new" => "tickets#new"

  #get "tickets#show"

  get "log_out" => "sessions#exit", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "create_account" => "users#new", :as => "create_account"
  root :to => "sessions#new"


  resources :users
  resources :sessions

  # Ticket updates as a sub-controller
  #resources :tickets do
  #  resources :ticket_updates
  #end

  resources :ticket_updates
  resources :tickets do
    resources :ticket_updates
  end
  #get 'tickets/:ticket_id/update' => 'tickets/ticket_update#new', :action => 'new'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password, :password_confirmation
  attr_accessible :password, :password_confirmation, :email, :first_name, :last_name, :photo
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_attached_file :photo,
    :styles => {
      :thumb => "100x100#",
      :small => "150x150>"
    }

  def self.authenticate(email, password)
    puts "Authenticating: ", email, "; ", password
    user = find_by_email(email)
    puts "User is: ", user
    if user
      puts "New encrypted PW:", BCrypt::Engine.hash_secret(password, user.password_salt)
      puts "Compared to: ", user.password_hash
    end

    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    puts "Encrypting password"
    if @password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(@password, self.password_salt)
    end
  end

  def self.get_current_user(user_id)
    if defined? user_id
      return find_by_id(user_id)
    else
      return nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if session[:user_id] == nil
      redirect_to root_url, :notice => "Please Log In"
      return
    end
    @users = User.all

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def new
    @user = User.new
  end

  def create
    puts "Creating User: ", params[:user]
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Account Successfully Created"
    else
      render "new"
    end
  end

  def show
    if session[:user_id] == nil
      redirect_to root_url, :notice => "Please Log In"
    else
      #@user = User.get_current_user session[:user_id]
      @user = User.find(params[:id])

      respond_to do |format|
        format.html
        format.json { render json: @user }
      end
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Modifying <%= @user.first_name %>'s profile</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.file_field :photo %>
  </p>

  <p class="button"><%= f.submit %></p>

  <%= link_to 'Cancel', users_path %>
<% end %>

app/views/users/index.html.erb
<h1>Listing of all registered Users</h1>

<table>
  <% @users.each do |user| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
        <% image_tag user.photo.url(:thumb) %>
      </td>
      <td class="list_info">
        <%= user.first_name %>
        ,
        <%= user.last_name %>
      </td>
      <td class="list_info">
        <%= user.email %>
      </td>
      <td class="list_info">
        <%= link_to 'Profile', user %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Account Creation</h1>

<%= form_for @user, :html =>  { :multipart => true } do |f| %>
  <% if @user.errors.any?  %>
    <div class="error_messages">
      <h2>Invalid Form</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.file_field :photo %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<h1>Profile for <%= @user.first_name %></h1>

<p>
  <%= image_tag @user.photo.url(:small) %>
</p>

<p>
  Username/Email: 
  <%= @user.email %>
</p>

<p>
  First name: 
  <%= @user.first_name %>
</p>

<p>
  Last name: 
  <%= @user.last_name %>
</p>

<% if @user.id == session[:user_id] %>
  <p class="button"><%= link_to "Edit Profile", edit_user_path(@user) %></p>
  <p class="button"><%= link_to "My Tickets", tickets_path %></p>
<% end %>