config/routes.rb
DynamicTicketingSystem::Application.routes.draw do

  get "tickets/new" => "tickets#new"

  #get "tickets#show"

  get "log_out" => "sessions#exit", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "create_account" => "users#new", :as => "create_account"
  root :to => "sessions#new"


  resources :users
  resources :sessions

  # Ticket updates as a sub-controller
  #resources :tickets do
  #  resources :ticket_updates
  #end

  resources :ticket_updates
  resources :tickets do
    resources :ticket_updates
  end
  #get 'tickets/:ticket_id/update' => 'tickets/ticket_update#new', :action => 'new'
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  # I feel like has_one should make more sense here.
  belongs_to :user
  belongs_to :status
  has_many :ticket_updates

  validates_presence_of :status, :name, :user

  # UID and SID are used to lookup the proper User and Statues when creating the Ticket. This needs to be done because HTML stores selections as strings
  attr_accessor :uid, :sid
  attr_accessible :description, :name, :uid, :sid, :user, :status

  def get_current_status
    set_latest_update

    if @latest_update
      return @latest_update.status
    else
      return self.status
    end
  end

  def get_current_owner
    set_latest_update

    if @latest_update
      return @latest_update.owner
    else
      return self.user
    end
  end

  def set_latest_update
    if not @latest_update
      @latest_update = TicketUpdate.where(["ticket_id = ?", self.id]).order("created_at").last
    end
  end

end

app/controllers/ticket/ticket_update_controller.rb
class Ticket::TicketUpdateController < ApplicationController
  def create
    if not session[:user_id]
      redirect_to root_url + "log_in", notice: 'Please login'
      return
    end

    respond_to do |format|
      puts "Creating ticket #{params[:ticket_update]}"
      if Ticket.create(params[:ticket_update])
        puts "Ticket Update successfully created"
        format.html { redirect_to @ticket_update, notice: 'Ticket Successfully Created' }
        format.json { render json: @ticket_update, status: :created, location: @ticket_update }
      else
        puts "Ticket Update creation failed", @ticket_update.errors.map { |attr, msg| msg }
        format.html { render action: "new" }
        format.json { render json: @ticket_update.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    if not session[:user_id]
      redirect_to root_url + "log_in", notice: 'Please login'
      return
    end

    @ticket_update = TicketUpdate.new
  end
end

app/controllers/tickets/ticket_update_controller.rb
class Tickets::TicketUpdateController < ApplicationController
  def create
    if not session[:user_id]
      redirect_to root_url + "log_in", notice: 'Please login'
      return
    end

    respond_to do |format|
      puts "Creating ticket #{params[:ticket_update]}"
      params[:ticket] = @ticket
      params[:updater] = User.find(session[:user_id])
      if Ticket.create(params[:ticket_update])
        puts "Ticket Update successfully created"
        format.html { redirect_to @ticket_update, notice: 'Ticket Successfully Created' }
        format.json { render json: @ticket_update, status: :created, location: @ticket_update }
      else
        puts "Ticket Update creation failed", @ticket_update.errors.map { |attr, msg| msg }
        format.html { render action: "new" }
        format.json { render json: @ticket_update.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    if not session[:user_id]
      redirect_to root_url + "log_in", notice: 'Please login'
      return
    end

    #@ticket = Ticket.find(params[:ticket_id])
    @ticket_update = TicketUpdate.new
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    if not session[:user_id]
      redirect_to root_url + "log_in", notice: 'Please login'
      return
    end

    @ticket = Ticket.new

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    if not session[:user_id]
      redirect_to root_url + "log_in", notice: 'Please login'
      return
    end

    params[:ticket][:user] = User.find_by_id params[:ticket][:uid].to_i
    params[:ticket][:status] = Status.find_by_id params[:ticket][:sid].to_i
    puts "Usr: #{params[:ticket][:user]} ; Status: #{params[:ticket][:status]}"

    respond_to do |format|
      puts "Creating ticket #{params[:ticket]}"
      if Ticket.create(params[:ticket])
        puts "Ticket successfully created"
        format.html { redirect_to @ticket, notice: 'Ticket Successfully Created' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        puts "Ticket creation failed", @ticket.errors.map { |attr, msg| msg }
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    if not session[:user_id]
      redirect_to root_url + "log_in", notice: 'Please login'
      return
    end
    @ticket = Ticket.find_by_id(params[:id])
    puts "Showing ticket:", @ticket
    puts "All tickets:", Ticket.all

    respond_to do |format|
      format.html
      format.json { render json: @ticket }
    end
  end

  def index
    if not session[:user_id]
      redirect_to root_url + "log_in", notice: 'Please login'
      return
    end
    
    @tickets = Ticket.all.select { |t| t.get_current_owner().id == session[:user_id] }
  end

  def edit
    puts "params are: ", params
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:user])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/tickets/edit.html.erb
<h1>Add Update to Ticket #<%= @ticket.id %></h1>

<!-- Ticket's information/current state (unchangable) -->
<table>
  <tr>
    <td>
      Ticket ID
    </td>
    <td>
      <%= @ticket.id %>
    </td>
  </tr>
  <tr>
    <td>
      Name
    </td>
    <td>
      <%= @ticket.name %>
    </td>
  </tr>
  <tr>
    <td>
      Status
    </td>
    <td>
      <%= @ticket.get_current_status().name %>
    </td>
  </tr>
  <tr>
    <td>
      Description
    </td>
    <td>
      <%= @ticket.description %>
    </td>
  </tr>
  <tr>
    <th>
      Update history
    </th>
  </tr>
</table>

<!-- Updatable information -->

<table>
  <%= form_for @ticket_updates do |f| %>
    <% if @ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @ticket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <tr>
      <td>
        <%= f.label 'Owner' %><br/>
      </td>
      <td>
        <%= f.select :uid, options_for_select(User.all.map { |x| [x.email, x.id] } ) %>
      </td>
    </tr>

    <tr>
      <td>
        <%= f.label :status %><br/>
      </td>
      <td>
        <%= f.select :sid, options_for_select(Status.all.map { |x| [x.name, x.id] } ) %>
      </td>
    </tr>

    <tr>
      <td>
        <%= f.label :description %>
      </td>
      <td>
        <%= f.text_field :description %>
      </td>
    </tr>

    <tr>
      <td>
        <%= f.label :time_logged %>
      </td>
      <td>
        <%= f.text_field :time_logged %>
      </td>
    </tr>

    <tr class="button"><%= f.submit "Update!" %></tr>
  <% end %>
</table>

app/views/tickets/index.html.erb
<h1>My Tickets</h1>

<p class="button"><%= link_to "Create New Ticket", new_ticket_path %></p>

<table border="0" >
  <tr>
    <td>
      Ticket ID
    </td>
    <td>
      Name
    </td>
    <td>
      Status
    </td>
    <td>
      Description
    </td>
  </tr>
  <% @tickets.each do |ticket| %>
    <tr class="clickable" onclick="document.location = '<%= root_url + "tickets/#{ticket.id}" %>'">
      <td>
        <%= ticket.id %>
      </td>
      <td>
        <%= ticket.name %>
      </td>
      <td>
        <%= ticket.get_current_status().name %>
      </td>
      <td>
        <%= ticket.description %>
      </td>
    </tr>
  <% end %>
</table>

app/views/tickets/new.html.erb
<h1>Create a new Ticket</h1>

<%= form_for @ticket do |f| %>
  <div class=field>
    <%= f.label :name %><br/>
    <%= f.text_field :name %><br/>
  </div>

  <div class=field>
    <%= f.label 'Owner' %><br/>
    <%= f.select :uid, options_for_select(User.all.map { |x| [x.email, x.id] } ) %>
  </div>

  <div class=field>
    <%= f.label :status %><br/>
    <%= f.select :sid, options_for_select(Status.all.map { |x| [x.name, x.id] } ) %>
  </div>

  <div class=field>
    <%= f.label :description %><br/>
    <%= f.text_field :description %><br/>
  </div>

  <div class=field>
    <%= f.submit "Create!" %>
  </div>
<% end %>

app/views/tickets/show.html.erb
<h1>Ticket #<%= @ticket.id %></h1>

<p>
  <%= link_to 'Update', new_ticket_ticket_update_path(@ticket) %>
</p>
<table>
  <tr>
    <td>
      Ticket ID
    </td>
    <td>
      <%= @ticket.id %>
    </td>
  </tr>
  <tr>
    <td>
      Name
    </td>
    <td>
      <%= @ticket.name %>
    </td>
  </tr>
  <tr>
    <td>
      Owner
    </td>
    <td>
      <%= @ticket.get_current_owner.email %>
    </td>
  </tr>
  <tr>
    <td>
      Status
    </td>
    <td>
      <%= @ticket.get_current_status.name %>
    </td>
  </tr>
  <tr>
    <td>
      Description
    </td>
    <td>
      <%= @ticket.description %>
    </td>
  </tr>
</table>

<% @ticket.ticket_updates.each do |tu| %>
  <div>
    <h3>Revision #<%= tu.revision %></h3>
    On <%= tu.created_at %>, <%= (tu.updater.first_name || '') + ", " + (tu.updater.last_name || '') %> spent <%= tu.time_logged %> hrs making the following change:
  </div>

  <p>
    <%= tu.description %>
  </p>
<% end %>