config/routes.rb
DynamicTicketingSystem::Application.routes.draw do

  get "tickets/new" => "tickets#new"

  #get "tickets#show"

  get "log_out" => "sessions#exit", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "create_account" => "users#new", :as => "create_account"
  root :to => "sessions#new"


  resources :users
  resources :sessions

  # Ticket updates as a sub-controller
  #resources :tickets do
  #  resources :ticket_updates
  #end

  resources :ticket_updates
  resources :tickets do
    resources :ticket_updates
  end
  #get 'tickets/:ticket_id/update' => 'tickets/ticket_update#new', :action => 'new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DynamicTicketingSystem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1 id="banner" class="boxed">
    <%= @app_name || "Dynamic Ticketing System" %>
  </h1>

    <% if not session[:user_id] %>
      <div id="jokes", class="boxed">
      <% joke = Joke.find(1) %>
      <%= joke.body %>
      </div>
    <% end %>


    <% if not flash.empty? %>
      <div id="messages", class="boxed">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
      </div>
    <% end %>

  <div id="columns">
    <div id="left" class="boxed">
      <% if session[:user_id] %>
        <p class="button"><%= link_to "My Profile", user_url(session[:user_id]) %></p>
        <p class="button"><%= link_to "My Tickets", tickets_url %></p>
        <p class="button"><%= link_to "Logout", root_url + "log_out" %></p>
      <% end %>
    </div>
    <div id="main" class="boxed">
      <%= yield %>
    </div>
    <div id="right" class="boxed">

    </div>
  </div>



</body>
</html>